component: website # (必填) 组件名称，此处为 apigateway
name: chat-interface # (必填) 实例名称
org: tencent # (可选) 用于记录组织信息，默认值为您的腾讯云账户 appid
app: nodejs-websocket # (可选) 该应用名称
stage: dev # (可选) 用于区分环境信息，默认值为 dev
inputs:
  src:
    src: ./
    index: client.html
  region: ${env:REGION}
  bucketName: chat-bucket
  protocol: http
