component: scf
name: wstrans
org: tencent
app: nodejs-websocket
stage: dev

inputs:
  name: ${name}-${stage}
  src: ./
  region: ${env:REGION}
  handler: transmit.main_handler
  runtime: Nodejs10.15
  environment:
    variables:
      apiid: api-pgrw7a14
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
