component: scf
name: wsdisconnect
org: tencent
app: nodejs-websocket
stage: dev

inputs:
  name: ${name}-${stage}
  src: ./
  runtime: Nodejs10.15
  region: ${env:REGION}
  handler: disconnect.main_handler
