component: scf
name: wsdisconnectTEST
org: tencent
app: wsAppTEST
stage: dev

inputs:
  name: ${name}-${stage}
  src: ./
  runtime: Nodejs10.15
  region: ${env:REGION}
  handler: disconnect.main_handler
