component: scf
name: wsconnect
org: tencent
app: nodejs-websocket
stage: dev

inputs:
  name: ${name}-${stage}
  src: ./
  runtime: Nodejs10.15
  region: ${env:REGION}
  handler: connect.main_handler
